### ISSUE TITLE
Failed to load seasonal compendium (1.20.1)

### ISSUE THREAD

**Issue by mpustovoi** [lucaargolo/fabric-seasons-extras#17]
I have the latest Minecraft 1.20.1 mods installed:
• Fabric Seasons Extras 1.2-BETA
• Patchouli-1.20.1-81- FABRIC

Seasonal compendium is enabled and does not work. Here is the error in the logs:
`[main/ERROR]: Failed to load book seasonsextras:seasonal_compendium defined by mod seasonsextras, skipping
java.lang.IllegalArgumentException: Book seasonsextras:seasonal_compendium has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.22.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]`

I'm sorry if such an issue has already been created.

**Comment by lucaargolo** [comment]
This should be fixed on version 1.3.1-BETA.
