### ISSUE TITLE
Invalid Player Data issue

### ISSUE THREAD

**Issue by droodgit** [lucaargolo/fabric-seasons-extras#2]
I am having trouble using this mod in conjunction with the main mod or any configuration of my other mods and getting booted from a freshly generated single player game with the message "Invalid Player Data", the Fabric Seasons mod itself works great. I have my logs saved from the moment it causes the error and was wondering if you could shed light on it? The error goes away if I remove this mod from my list.
```
[22:46:36] [Server thread/ERROR]: Couldn't place player in world
io.netty.handler.codec.EncoderException: String too big (was 25991069 characters, max 32767)
	at net.minecraft.class_2540.method_10788(class_2540.java:617) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10814(class_2540.java:612) ~[client-intermediary.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.lambda$sendMultiblocks$27(FabricSeasonsExtras.java:255) ~[fabric-seasons-extras-1.1-BETA+1.19.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.sendMultiblocks(FabricSeasonsExtras.java:253) ~[fabric-seasons-extras-1.1-BETA+1.19.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.sendValidBiomes(FabricSeasonsExtras.java:176) ~[fabric-seasons-extras-1.1-BETA+1.19.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.lambda$onInitialize$4(FabricSeasonsExtras.java:131) ~[fabric-seasons-extras-1.1-BETA+1.19.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.2.11+10eb22f490-f06f04cf50fd31dd.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:65) ~[fabric-networking-api-v1-1.2.11+10eb22f490-f06f04cf50fd31dd.jar:?]
	at net.minecraft.class_3324.handler$def000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:7513) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:200) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:138) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$deg000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:73) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[client-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[22:46:36] [Server thread/INFO]: KingBendrick lost connection: Invalid player data
[22:46:36] [Server thread/INFO]: KingBendrick left the game
```
Thanks and great job on the mod, I love the concept for an animal crossing type setup I'm working on!

**Comment by lucaargolo** [comment]
Can you try using this mod to increase the packet size? https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric

**Comment by droodgit** [comment]
I just tried again with both and it still gave the error but the max string size seems to be the same?

here is the mod as per the load:
```
	- xlpackets 1.19.2-4
```
and here is the same error:
```
[02:58:53] [Server thread/ERROR]: Couldn't place player in world
io.netty.handler.codec.EncoderException: String too big (was 4769037 characters, max 32767)
	at net.minecraft.class_2540.method_10788(class_2540.java:617) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10814(class_2540.java:612) ~[client-intermediary.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.lambda$sendMultiblocks$27(FabricSeasonsExtras.java:255) ~[fabric-seasons-extras-1.1-BETA+1.19.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.sendMultiblocks(FabricSeasonsExtras.java:253) ~[fabric-seasons-extras-1.1-BETA+1.19.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.sendValidBiomes(FabricSeasonsExtras.java:176) ~[fabric-seasons-extras-1.1-BETA+1.19.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.lambda$onInitialize$4(FabricSeasonsExtras.java:131) ~[fabric-seasons-extras-1.1-BETA+1.19.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.2.11+10eb22f490-f06f04cf50fd31dd.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:65) ~[fabric-networking-api-v1-1.2.11+10eb22f490-f06f04cf50fd31dd.jar:?]
	at net.minecraft.class_3324.handler$eam000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:7513) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:200) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:138) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$ean000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:73) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[client-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by lucaargolo** [comment]
Alright, I'll take a look at it tomorrow and try to fix it.

**Comment by MCRusher** [comment]
Just wanted to say I'm also having the same issue.

Using Quilt on 1.19.2.

The interesting thing is that if I only run Mod Menu, Quilt Fabric API, Fabric Seasons, and Fabric Seasons Extras it works fine.

So it seems to be a combo of this mod and another causing the issue.

I'll try seeing what mod in my list triggers this mod to fail.

**Comment by MCRusher** [comment]
@lucaargolo I think I found the problematic mods, or at least a related issue

The incompatibility is isolated with this mod list:

- [QFAPI](https://modrinth.com/mod/qsl/version/4.0.0-beta.30+0.76.0-1.19.2)
- [Fabric Seasons](https://modrinth.com/mod/fabric-seasons/version/2.0+1.19)
- [Fabric Seasons Extras](https://modrinth.com/mod/fabric-seasons-extras/version/1.1-BETA+1.19)
- [Patchouli](https://modrinth.com/mod/patchouli/version/1.19.2-77-fabric)
- [FastLoad](https://modrinth.com/mod/fastload/version/3.3.8)

When FastLoad is disabled, it works
When Patchouli is disabled, it works
When Fabric Seasons Extras is disabled, it works

So the error only seems to be triggered when these three mods are all present at once.

I also tried using [XXLPackets](https://modrinth.com/mod/xxl-packets) like suggested along with this mod list, didn't work

Here's the whole error message when I try to join/create a singleplayer world:

```[22:26:17] [Server thread/ERROR]: Couldn't place player in world
io.netty.handler.codec.EncoderException: String too big (was 6609236 characters, max 32767)
	at net.minecraft.class_2540.method_10788(class_2540.java:617) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2540.method_10814(class_2540.java:612) ~[transformed-mod-minecraft.i0:0/:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.lambda$sendMultiblocks$27(FabricSeasonsExtras.java:255) ~[transformed-mod-seasonsextras.i0:0/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.sendMultiblocks(FabricSeasonsExtras.java:253) ~[transformed-mod-seasonsextras.i0:0/:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.sendValidBiomes(FabricSeasonsExtras.java:176) ~[transformed-mod-seasonsextras.i0:0/:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.lambda$onInitialize$4(FabricSeasonsExtras.java:131) ~[transformed-mod-seasonsextras.i0:0/:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$3(ServerPlayConnectionEvents.java:51) ~[transformed-mod-quilted-fabric-networking-api-v1.i0:0/:?]
	at org.quiltmc.qsl.networking.api.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[transformed-mod-quilt-networking.i0:0/:?]
	at org.quiltmc.qsl.networking.impl.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:68) ~[transformed-mod-quilt-networking.i0:0/:?]
	at net.minecraft.class_3324.handler$znp000$quilt_networking$handlePlayerConnection(class_3324.java:2513) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:200) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:151) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:138) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3248.redirect$zoa000$quilt_networking$handlePlayerJoin(class_3248.java:1058) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:73) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:98) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[transformed-mod-minecraft.i0:0/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

Hope this helps.
