### ISSUE TITLE
fabric 1.19.2 with fabric-seasons-extras-1.2-BETA+1.19.jar

### ISSUE THREAD

**Issue by jg2002-j** [lucaargolo/fabric-seasons-extras#21]
when creating a singleplayer the window just crashes:

```
[16:28:41] [spark-java-sampler-0-1/WARN]: Timed out waiting for world statistics
[16:28:43] [spark-java-sampler-0-4/WARN]: Timed out waiting for world statistics
[16:28:49] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.resize(HashMap.java:702) ~[?:?]
	at java.util.HashMap.putVal(HashMap.java:661) ~[?:?]
	at java.util.HashMap.put(HashMap.java:610) ~[?:?]
	at java.util.HashSet.add(HashSet.java:221) ~[?:?]
	at net.minecraft.class_2944.method_43162(class_2944.java:142) ~[client-intermediary.jar:?]
	at net.minecraft.class_2944$$Lambda$30230/0x0000000803576d68.accept(Unknown Source) ~[?:?]
	at net.frozenblock.wilderwild.world.generation.trunk.BaobabTrunkPlacer.setDirtAt(BaobabTrunkPlacer.java:246) ~[WilderWild-2.0.6-Fabric+1.19.2.jar:?]
	at net.frozenblock.wilderwild.world.generation.trunk.BaobabTrunkPlacer.terraformDirtBelow(BaobabTrunkPlacer.java:237) ~[WilderWild-2.0.6-Fabric+1.19.2.jar:?]
	at net.frozenblock.wilderwild.world.generation.trunk.BaobabTrunkPlacer.method_26991(BaobabTrunkPlacer.java:92) ~[WilderWild-2.0.6-Fabric+1.19.2.jar:?]
	at net.minecraft.class_2944.method_12775(class_2944.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_2944.method_13151(class_2944.java:154) ~[client-intermediary.jar:?]
	at net.minecraft.class_3031.method_40163(class_3031.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:27) ~[client-intermediary.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.lambda$sendBiomeMultiblocks$15(FabricSeasonsExtras.java:197) ~[fabric-seasons-extras-1.2-BETA+1.19.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras$$Lambda$31246/0x0000000803709268.generate(Unknown Source) ~[?:?]
	at io.github.lucaargolo.seasonsextras.patchouli.PatchouliMultiblockCreator.getMultiblock(PatchouliMultiblockCreator.java:60) ~[fabric-seasons-extras-1.2-BETA+1.19.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.lambda$sendBiomeMultiblocks$24(FabricSeasonsExtras.java:199) ~[fabric-seasons-extras-1.2-BETA+1.19.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras$$Lambda$31235/0x0000000803701450.accept(Unknown Source) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.sendBiomeMultiblocks(FabricSeasonsExtras.java:183) ~[fabric-seasons-extras-1.2-BETA+1.19.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.lambda$sendValidBiomes$13(FabricSeasonsExtras.java:173) ~[fabric-seasons-extras-1.2-BETA+1.19.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras$$Lambda$31229/0x0000000803703360.accept(Unknown Source) ~[?:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.sendValidBiomes(FabricSeasonsExtras.java:158) ~[fabric-seasons-extras-1.2-BETA+1.19.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras.lambda$onInitialize$4(FabricSeasonsExtras.java:131) ~[fabric-seasons-extras-1.2-BETA+1.19.jar:?]
	at io.github.lucaargolo.seasonsextras.FabricSeasonsExtras$$Lambda$17653/0x0000000802300de8.onPlayReady(Unknown Source) ~[?:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents$$Lambda$4400/0x0000000800e366e8.onPlayReady(Unknown Source) ~[?:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:65) ~[fabric-networking-api-v1-1.2.12+def3f86d90-40dbcfca42bb4b90.jar:?]
	at net.minecraft.class_3324.handler$eha000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:6513) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:200) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:151) ~[client-intermediary.jar:?]
[16:28:49] [Server thread/ERROR]: This crash report has been saved to: C:\Users\jgand\curseforge\minecraft\Instances\fabrique\crash-reports\crash-2023-10-10_16.28.49-server.txt
[16:28:49] [Server thread/INFO]: [STDOUT]: Saving server results
[16:28:49] [spark-java-sampler-0-1/INFO]: [STDERR]: java.util.concurrent.RejectedExecutionException: Server already shutting down
[16:28:49] [spark-java-sampler-0-1/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_40000(MinecraftServer.java:1246)
[16:28:49] [spark-java-sampler-0-1/INFO]: [STDERR]: 	at me.lucko.spark.fabric.plugin.FabricServerSparkPlugin.executeSync(FabricServerSparkPlugin.java:146)
[16:28:49] [spark-java-sampler-0-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782)
[16:28:49] [spark-java-sampler-0-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005)
[16:28:49] [spark-java-sampler-0-1/INFO]: [STDERR]: 	at me.lucko.spark.common.platform.world.AsyncWorldInfoProvider.async(AsyncWorldInfoProvider.java:54)

```

**Comment by Maloonkey** [comment]
There's a weird interaction with Wilder Wild and Extras, I've replicated this crash as well. Some weird memory leak and I ruled out all other possible mods in a modpack containing the two.

**Comment by Conobi** [comment]
Can confirm the crash!
